// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44348' | (string & {});
};

export type OEmbedResponse = {
    type: string;
    version: string;
    title: string;
    authorName: string;
    authorUrl: string;
    providerName: string;
    providerUrl: string;
    thumbnailUrl: string;
    thumbnailHeight?: number | null;
    thumbnailWidth?: number | null;
    html: string;
    url: string;
    height?: number | null;
    width?: number | null;
    cacheAge?: number | null;
};

export type GetUmbracoOembedGetData = {
    body?: never;
    path?: never;
    query?: {
        url?: string;
        maxWidth?: number;
        maxHeight?: number;
    };
    url: '/umbraco/oembed/get';
};

export type GetUmbracoOembedGetErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetUmbracoOembedGetResponses = {
    /**
     * OK
     */
    200: OEmbedResponse;
};

export type GetUmbracoOembedGetResponse = GetUmbracoOembedGetResponses[keyof GetUmbracoOembedGetResponses];
